name: Deploy to Production

on:
  push:
    branches:
      - US-*
      - master

jobs:
  deploy:
    name: Deploy to Jira
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Jira issue key from branch name
        id: extract
        run: |
          echo "Branch name: ${{ github.ref }}"
          ISSUE_KEY=$(echo "${{ github.ref }}" | grep -oE '[A-Z]+-[0-9]+' || true)
          echo "Extracted Jira issue key: $ISSUE_KEY"
          echo "jira_key=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Create GitHub Deployment
        id: create_deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          ref: ${{ github.ref }}

      - name: Update Deployment Status to Success
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: success
