name: Deployment Notification  # Назва workflow, яка відображатиметься у вкладці "Actions" в GitHub

on:
  pull_request:               # Коли запускати workflow:
    branches:                 # ... при створенні або оновленні pull request у такі гілки:
      - master                # головна гілка
      - US-*                  # всі гілки, що починаються з "US-" (наприклад, US-123)

jobs:
  deploy:                     # Назва job'а (довільна, але логічна)
    runs-on: ubuntu-latest    # GitHub створить віртуальну машину з Ubuntu для виконання кроків

    steps:                    # Послідовні дії, які виконує job
      - name: Notify Jira of deployment   # 2️⃣ Надіслати інформацію про розгортання в Jira
        uses: atlassian/gajira-deployments@v1
        with:
          site: ${{ secrets.ninesquares.atlassian.net }}             # Jira сайт (наприклад, yourteam.atlassian.net)
          email: ${{ secrets.pm@ninesquares.studio }}           # Email Atlassian-акаунта
          api-token: ${{ secrets.ATATT3xFfGF0XEDy8pPctaJ30NjaGXSeIXILXvFOsEeKfvFfoyHXSOTUymFC8kRrmz989U-9Mn3LuyCiPgf3BGw1Z2B1uyNwbzLZdNFJuyrSSXT5BFxwNflHLv5vNJjEIhPSqNI6SX6UjbRACmkCRaPboWaDKigt_hFrsdaZwT4asf8ELLJ4kR0=C36E12E6 }}   # Jira API токен
          environment: production                       # Назва середовища (можеш змінити на "production")
          environment-type: production                   # Тип середовища: development / staging / production
