name: Deploy using shared template

on:
  push:
    branches:
      - master
      - US-*

jobs:
  deploy:
    uses: yourcompany/workflow-templates/.github/workflows/deploy.yml@main
    with:
      environment: production
