name: Deploy using shared template

on:
  push:
    branches:
      - master
      - US-*
      - US1-*

jobs:
  deploy:
    uses: 9Ninesquares/workflow-templates/.github/workflows/deploy.yml@main
    with:
      environment: production
