name: Deployment Notification  # Назва workflow, яка відображатиметься у вкладці "Actions" в GitHub

on:
  pull_request:               # Коли запускати workflow:
    branches:                 # ... при створенні або оновленні pull request у такі гілки:
      - master                # головна гілка
      - US-*                  # всі гілки, що починаються з "US-" (наприклад, US-123)

jobs:
  deploy:                     # Назва job'а (довільна, але логічна)
    runs-on: ubuntu-latest    # GitHub створить віртуальну машину з Ubuntu для виконання кроків

    steps:                    # Послідовні дії, які виконує job
      - name: Checkout code   # 1️⃣ Назва першого кроку — "Отримати код з репозиторію"
        uses: actions/checkout@v3
        # Використовує офіційний GitHub Action для завантаження (checkout) коду з репозиторію
        # Це обов’язково, якщо ти хочеш працювати з файлами проекту, але у цьому випадку — не обов’язково.
        # Можеш цей крок видалити, якщо не виконуєш тести чи збірку.

      - name: Notify Jira of deployment   # 2️⃣ Надіслати інформацію про розгортання в Jira
        uses: atlassian/gajira-deployments@v1
        with:
          site: ${{ secrets.JIRA_SITE }}             # Jira сайт (наприклад, yourteam.atlassian.net)
          email: ${{ secrets.JIRA_EMAIL }}           # Email Atlassian-акаунта
          api-token: ${{ secrets.JIRA_API_TOKEN }}   # Jira API токен
          environment: staging                        # Назва середовища (можеш змінити на "production")
          environment-type: staging                   # Тип середовища: development / staging / production
